name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      codescan_org: 'pet-store'
      codescan_project_key: 'pet-store-actions'
      codescan_token: ${{ secrets.codescan_token }}

    steps:
    - name: Info
      env:  
        ref: ${{ github.ref }}
        base_ref: ${{ github.base_ref }}
        head_ref: ${{ github.head_ref }}
        event_name: ${{ github.event_name }}
      run: |
        echo $ref
        echo $base_ref
        echo $head_ref
        echo $event_name
          
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install SFDX
      env:
        SFDX_AUTOUPDATE_DISABLE: false
        SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
        SFDX_DOMAIN_RETRY: 300
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE: true
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE: true
      run: |
        wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        export PATH=./sfdx/$(pwd):$PATH
        # Output CLI version and plug-in information
        sfdx update
        sfdx --version
        sfdx plugins --core
 
        # Install the CodeScan plugin using the Salesforce CLI
        # The echo is to accept that the plugin is unsigned.
        echo y|sfdx plugins:install sfdx-codescan-plugin
        # Output the plug-in information
        sfdx plugins

    - name: Run Codescan On Push
      if: github.event_name == 'push'
      run: |
        sfdx codescan:run --token $codescan_token --projectkey $codescan_project_key --organization $codescan_org 

    - name: Run Codescan On PR
      if: github.event_name == 'pull_request'
      env:  
        branch_name: ${{ github.ref }}
        target: ${{github.base_ref}}
        branch_type: SHORT 
      run: |
        sfdx codescan:run --token $codescan_token --projectkey $codescan_project_key --organization $codescan_org -Dsonar.branch.name=$branch_name -Dsonar.branch.target=$target
          
